/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.adobe.sign.api;

import com.adobe.sign.model.ApiException;
import com.adobe.sign.model.groups.DetailedGroupInfo;
import com.adobe.sign.model.groups.GroupUsersInfo;
import com.adobe.sign.model.groups.GroupsInfo;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for GroupsApi
 */
@Ignore
public class GroupsApiTest {

    private final GroupsApi api = new GroupsApi();

    
    /**
     * Retrieves detailed information about the group.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupDetailsTest() throws ApiException {
        String authorization = null;
        String groupId = null;
        String xApiUser = null;
        DetailedGroupInfo response = api.getGroupDetails(authorization, groupId, xApiUser);

        // TODO: test validations
    }
    
    /**
     * Retrieves all the groups in an account.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupsTest() throws ApiException {
        String authorization = null;
        String xApiUser = null;
        String cursor = null;
        Integer pageSize = null;
        GroupsInfo response = api.getGroups(authorization, xApiUser, cursor, pageSize);

        // TODO: test validations
    }
    
    /**
     * Retrieves all the users in a group.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsersInGroupTest() throws ApiException {
        String authorization = null;
        String groupId = null;
        String xApiUser = null;
        String cursor = null;
        Integer pageSize = null;
        GroupUsersInfo response = api.getUsersInGroup(authorization, groupId, xApiUser, cursor, pageSize);

        // TODO: test validations
    }
    
}
